name: voici
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - ipywidgets
  - numpy
  - pandas
  - matplotlib
  # Add only pure-Python (noarch) or emscripten-forge packages here
