
name: Build JupyterLite site
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install jupyterlite==0.4.* jupyterlite-core jupyterlite-pyodide-kernel
      - run: jupyter lite build --contents content --output-dir _output
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _output
      - uses: actions/deploy-pages@v4
