name: Build JupyterLite site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install JupyterLite + widgets
        run: |
          pip install "jupyterlite==0.4.*" "jupyterlite-core==0.4.*" "jupyterlite-pyodide-kernel==0.4.*" \
                      "jupyter_server>=2,<3" "jupyterlab_widgets==3.*"

      - name: Clean previous build
        run: jupyter lite clean

      - name: Build site (bundle widgets manager)
        run: >
          jupyter lite build --contents content --output-dir _output
          --federated-extensions "@jupyter-widgets/jupyterlab-manager@5.0.10"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
